name: Build AlfaGUI Windows App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Zip build folder
        run: |
          Compress-Archive -Path ".\build\windows\x64\runner\Release" -DestinationPath "windows-release.zip" -Force

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: windows-release.zip
