name: Build release for Alfa CR GUI Windows App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Imposta MY_WORKSPACE variabile
        shell: pwsh
        run: |
          echo "MY_WORKSPACE=$env:GITHUB_WORKSPACE" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Mostra percorso MY_WORKSPACE
        shell: pwsh
        run: |
          Write-Output "Il percorso di GITHUB_WORKSPACE è $env:MY_WORKSPACE"
      
      - name: Get app version and build from pubspec.yaml
        shell: pwsh
        run: |
          $yamlPath = Join-Path $env:MY_WORKSPACE "pubspec.yaml"
          $content = Get-Content $yamlPath -Raw
          $versionLine = $content -split "`n" | Where-Object { $_ -match '^\s*version\s*:\s*' }
          $version = $versionLine -replace '^\s*version\s*:\s*', ''
          $versionParts = $version -split '\+'
          $mainVersion = $versionParts[0].Trim()
          $buildNumber = $versionParts[1].Trim()

          $formattedVersion = "v$mainVersion`_build$buildNumber"
          echo "APP_FORMATTED_VERSION=$formattedVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Usa la versione formattata
        shell: pwsh
        run: |
          Write-Output "La versione formattata è: $env:FORMATTED_VERSION"

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: alfa-cr-gui_${{ env.FORMATTED_VERSION }}
          path: .\build\windows\x64\runner\Release\
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          tag: ${{ env.APP_FORMATTED_VERSION }}
          name: Release ${{ env.APP_FORMATTED_VERSION }}
          draft: false
          prerelease: false
          artifacts: |
            .\build\windows\x64\runner\Release\alfa-cr-gui_*
