name: Build release for Alfa CR GUI Windows App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Imposta MY_WORKSPACE variabile
        shell: pwsh
        run: |
          echo "MY_WORKSPACE=$env:GITHUB_WORKSPACE" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Mostra percorso MY_WORKSPACE
        shell: pwsh
        run: |
          Write-Output "Il percorso di GITHUB_WORKSPACE è $env:MY_WORKSPACE"

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      # - name: Parse pubspec.yaml
      #   uses: jonabc/read-yaml@v1
      #   id: parse_yaml
      #   with:
      #     path: pubspec.yaml
      #     key: version

      # - name: Set Version and Build Variables
      #   shell: pwsh
      #   run: |
      #     $versionParts = "${{ steps.parse_yaml.outputs.version }}" -split '\+'
      #     $version = $versionParts[0]
      #     $build = $versionParts[1]
      #     Write-Output "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      #     Write-Output "BUILD=$build" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # - name: Build Windows Release
      #   run: flutter build windows --release

      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: alfa-cr-gui_v${{ env.VERSION }}_build${{ env.BUILD }}
      #     path: .\build\windows\x64\runner\Release\
